cluster_name: pemdemo
cluster_tag: tag_Cluster_pemdemo
edb_repositories:
- enterprise
postgres_databases:
- extensions:
  - name: edb_wait_states
  - name: sql_profiler
  - name: index_advisor
  extra_postgres_packages:
  - edb-as15-server-edb_wait_states
  - edb-as15-server-sqlprofiler
  - edb-as15-server-indexadvisor
  name: edb
  preload_extensions:
  - edb_wait_states
  - sql-profiler
  - index-advisor
postgres_flavour: epas
postgres_version: '15'
ssh_key_file: id_pemdemo
tpa_version: '23.28'
use_volatile_subscriptions: true
yum_repository_list:
- EPEL
