---
architecture: M1
cluster_name: pemdemo
cluster_tags: {}

cluster_vars:
  edb_repositories:
  - enterprise
  postgres_flavour: epas
  postgres_version: '15'
  use_volatile_subscriptions: true
  yum_repository_list:
  - EPEL

locations:
- Name: main

instance_defaults:
  image: tpa/rocky:8
  platform: docker
  vars:
    ansible_user: root

postgres_databases:
- name: edb
  extensions:
  - name: edb_wait_states
#  - name: sql_profiler
#  - name: index_advisor
extra_postgres_packages:
- edb-as15-server-edb-wait-states
#- edb-as15-server-sqlprofiler
#- edb-as15-server-indexadvisor
preload_extensions:
- edb_wait_states
#- sql-profiler
#- index-advisor

instances:
- Name: pg1
  location: main
  node: 1
  role:
  - pem-agent

- Name: pemserver
  location: main
  node: 2
  role:
  - pem-server
  exposed_ports:
  - 443
 # published_ports:
 # - 433:433